name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install dependencies
      run: git submodule update --init --recursive
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
    - uses: actions/upload-artifact@v3
      with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk
